version: "3.3"
services:
  redeye:
    container_name: "Redeye"
    image: "redeyeframework/redeye:latest"
    ports:
      - "8443:8443"
    volumes:
      - Files:/redeye/files
      - DB:/redeye/RedDB

volumes:
  Files:
  DB:
  NeoData:
  NeoLogs:
  NeoImport:
  NeoPlugins: