version: "3.3"
services:
  redeye:
    container_name: "Redeye"
    image: "redeyeframework/redeye:latest"
    ports:
      - "8443:8443"
    links:
      - "neo4j:neo4j"
    volumes:
      - Files:/redeye/files
      - DB:/redeye/RedDB
  neo4j:
    image: "neo4j:latest"
    ports:
      - "0.0.0.0:7474:7474"
      - "0.0.0.0:7687:7687"
    env_file:
      - graph.env

volumes:
  Files:
  DB: